TRAINING_DATA = [
    # ---- RAG (interpretive) ----
    ("Can I claim HRA if I live with my parents?", "rag"),
    ("What is covered under Section 80D?", "rag"),
    ("Is PPF eligible for 80C deduction?", "rag"),
    ("What's the difference between old and new tax regime?", "rag"),
    ("Do I need proof to claim HRA exemption?", "rag"),
    ("What is the standard deduction amount?", "rag"),
    ("Can I claim both HRA and home loan interest?", "rag"),
    ("Is health insurance for my parents deductible?", "rag"),
    ("What happens if I don't choose a regime while filing?", "rag"),
    ("Explain how Section 87A rebate works.", "rag"),
    ("Is ELSS covered under 80C?", "rag"),
    ("What's the maximum I can claim under 80C?", "rag"),
    ("Does the new regime allow any deductions at all?", "rag"),
    ("Can self-employed individuals claim HRA?", "rag"),
    ("What counts as proof of rent payment?", "rag"),
    ("Is life insurance premium deductible?", "rag"),
    ("Who is eligible for the 87A rebate?", "rag"),
    ("Can I switch regimes every year?", "rag"),
    ("What is Section 16(ia) about?", "rag"),
    ("Does 80D cover dental treatment?", "rag"),
    ("Is tuition fee for children deductible under 80C?", "rag"),
    ("What documents do I need for HRA claims?", "rag"),
    ("Can NRIs claim these deductions?", "rag"),
    ("What's the senior citizen limit for 80D?", "rag"),
    ("Is there a deduction for home loan principal?", "rag"),

    # ---- Computational ----
    ("My income is 12,00,000, what's my tax under the old regime?", "compute"),
    ("I earn 18 lakh annually, calculate my tax.", "compute"),
    ("What would I owe if my salary is 9 lakhs with no deductions?", "compute"),
    ("Compute my tax for an income of 25 lakh under the new regime.", "compute"),
    ("I make 15 lakhs a year, what's my final tax liability?", "compute"),
    ("How much tax do I pay on 7 lakh income?", "compute"),
    ("Calculate tax for 20 lakh salary, 1.5 lakh in PPF.", "compute"),
    ("What's my tax if I earn 11 lakhs with 50k health insurance?", "compute"),
    ("Tax liability for income of 30 lakhs please.", "compute"),
    ("I want my exact tax amount for a 14 lakh salary.", "compute"),
    ("How much will I owe the government on 16 lakh income?", "compute"),
    ("Find my tax payable, income is 22 lakh.", "compute"),
    ("What's the tax on 6 lakh annual income?", "compute"),
    ("Give me the exact number I owe for 19 lakhs.", "compute"),
    ("Calculate liability: 13 lakh income, no deductions.", "compute"),
    ("What's my break-even deduction between regimes for 15 lakh income?", "compute"),
    ("Work out my tax, I make 8.5 lakhs freelancing.", "compute"),
    ("Final tax amount for 21 lakh salary, old regime.", "compute"),
    ("I earn 10 lakh, no investments, what do I pay?", "compute"),
    ("Number crunching time: 17 lakh income, what's owed?", "compute"),
    ("What's my liability on a 24 lakh package?", "compute"),
    ("Just give me the tax figure for 12.5 lakh income.", "compute"),
    ("Compute amount payable for 9.5 lakh salary.", "compute"),
    ("How much tax for 28 lakh under new regime?", "compute"),
    ("What do I owe on 5.5 lakh income?", "compute"),

    # ---- Both ----
    ("Can I claim HRA and what would my final tax be if I do?", "both"),
    ("I pay rent to my parents, how much tax would I save and what's my final liability?", "both"),
    ("Explain 80C and tell me my tax if I invest the full amount, income 15 lakh.", "both"),
    ("Is health insurance deductible, and what's my tax with a 25k premium on 12 lakh income?", "both"),
    ("What's HRA eligibility and my tax owed if I claim 2 lakh HRA on 18 lakh salary?", "both"),
    ("Explain the old vs new regime and tell me which is better for my 20 lakh income.", "both"),
    ("Can I claim 80D and what's my total tax with income 14 lakh and premium 30k?", "both"),
    ("Tell me about 87A rebate and compute my tax for 10 lakh income.", "both"),
    ("What deductions can I use and what would my tax be on a 16 lakh salary?", "both"),
    ("Explain HRA rules and calculate my savings on 2.5 lakh rent, income 17 lakh.", "both"),
    ("Am I eligible for 80C and what's my tax after claiming it, income 13 lakh?", "both"),
    ("Explain standard deduction and compute my final tax for 11 lakh income.", "both"),
    ("What counts toward 80C, and what's my tax if I max it out, salary 19 lakh?", "both"),
    ("Tell me if NRIs get HRA and what the tax would be for 22 lakh income.", "both"),
    ("Explain the regime difference and calculate which saves more for 25 lakh salary.", "both"),
    ("What's covered under 80D and my tax bill if I claim 25k, income 9 lakh?", "both"),
    ("Is home loan interest deductible and what's my tax including it, income 16 lakh?", "both"),
    ("Explain HRA proof requirements and compute my liability, income 14 lakh, rent 3 lakh.", "both"),
    ("What's the 87A limit and is my 11 lakh income tax-free under new regime?", "both"),
    ("Tell me about tuition fee deduction and my tax if I claim it, income 12 lakh.", "both"),
]
